#Projeto de Mad Libs

clima = input("Digite um clima: ")
print("====================================================================")
nome_menina = input("Digite o nome da menina: ")
print("====================================================================")
nome_parque = input("Digite o nome do parque: ")
print("====================================================================")
emoção = input("Digite uma emoção: ")
print("====================================================================")
adjetivo_1 = input("Digite um adjetivo: ")
print("====================================================================")
adjetivo_2 = input("Digite outro adjetivo: ")
print("====================================================================")
lugar_parque = input("Digite um lugar do parque: ")
print("====================================================================")
animal_1 = input("Digite um animal: ")
print("====================================================================")
verbo = input("Digite um verbo: ")
print("====================================================================")
coisa_inesperada = input("Digite algo inesperado: ")
print("====================================================================")
adverbio = input("Digite um advérbio: ")
print("====================================================================")
animal_2 = input("Digite outro animal: ")
print("====================================================================")
ação_engraçada = input("Digite uma ação engraçada: ")
print("====================================================================")
outra_emoção = input("Digite outra emoção: ")
print("====================================================================")
verbo_passado = input("Digite um verbo no passado: ")
print("====================================================================")

print(f"\n\"Um dia de {clima}, a pequena {nome_menina} decidiu andar de bicicleta no {nome_parque}. Ela estava {emoção} e pronta para explorar. Com suas {adjetivo_1} tranças ao vento e um sorriso {adjetivo_2} no rosto, ela começou a pedalar.\n\nEnquanto passeava pelo {lugar_parque}, viu um {animal_1} brincando perto do lago. Ela {verbo} para observá-lo e de repente, uma {coisa_inesperada} aconteceu. Ela riu {adverbio} quando o {animal_2} fez uma {ação_engraçada}.\n\nAo final do dia, a {nome_menina} estava {outra_emoção} e cheia de histórias para contar sobre sua aventura de bicicleta no {nome_parque}. Foi um dia que ela sempre {verbo_passado} com carinho.\"\n")

#by Paulo_Vinicius :)